.. NOTE: we are now using links to highlight new functions and classes.
   Please follow the examples below like 
   :func:`julearn.api.run_cross_validation`, so the
   whats_new page will have a link to the function/class documentation.

.. NOTE: there are 3 separate sections for changes, based on type:
   - "Enhancements" for new features
   - "Bugs" for bug fixes
   - "API changes" for backward-incompatible changes

.. _changes_0_0_1:

0.0.1
-----

Enhancements
~~~~~~~~~~~~

- Initial release by `Fede Raimondo`_.

- Created a the repository based on the mockup by `Fede Raimondo`_.

Bugs
~~~~

API changes
~~~~~~~~~~~
