.. NOTE: we are now using links to highlight new functions and classes.
   Please follow the examples below like 
   :func:`julearn.api.run_cross_validation`, so the
   whats_new page will have a link to the function/class documentation.

.. NOTE: there are 3 separate sections for changes, based on type:
   - "Enhancements" for new features
   - "Bugs" for bug fixes
   - "API changes" for backward-incompatible changes

.. _changes_0_0_2:

0.0.2
-----

Enhancements
~~~~~~~~~~~~

- Add Rank Selection using permutation by `Fede Raimondo`_ and `Kaustubh Patil`_.

- Support `"auto"` or `range` as `n_components` in OPNMF model by `Fede Raimondo`_. 

Bugs
~~~~

API changes
~~~~~~~~~~~
